#!/bin/sh
# # x-awk -- POSIX awk on x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus AWK,
#   with no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# THE LAUNCHER-FREE BOOT AMALGAM IS x-base.x, AND IT IMAGES.  Its compiled
# tower was the one thing a state image could not hold -- native analysers
# in pages of the writing process, which no name reacquires elsewhere --
# so for one day (2026-09-05) this harness booted x-core.x and imported the
# tower interpreted to get an image at all.  Two things closed that.  The
# platform's writer now un-JITs every compile site before its walk and the
# loader re-JITs them after the install (docs/state-images.md, "Compiled
# code: put down before the write, picked up after the load"), so the
# tower travels as the sources it was compiled from.  And the engine's
# `def` scopes by the live frame instead of the save stack (x-engine-c
# v0.2.8, #41): the asm cache's own tail-position defs had been leaking
# into globals the writer could not name, on a cold byte cache above all,
# which is the case CI sees.  On that engine x-base.x writes clean, and
# `make images` in the platform lists it.  tests/spec-runner.sh writes
# and uses the image; a platform whose engine predates the pin refuses
# the write and the suite boots from source, which is only slower.
#
# An install has the amalgam at boot/, a checkout builds it into
# build/boot/.  lib/x-base.x is NOT a substitute -- it opens with a
# root-relative include.  (Same probe as x-ash; see its notes.)
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-awk: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# A KNOWN GAP, RECORDED HERE BECAUSE THIS IS WHERE IT WOULD HIDE: the tower
# x-base.x boots is one `x -l awk` never loads.  The bundle declares
# dialect he and awk/prims.x imports float alone, so every fraction in the
# shipped lang truncates -- 0 for 1/4, 2 for exp(1), 0 for a 0.25 literal
# -- while this suite, on x-base.x's tower, stays green (found 2026-09-05,
# by a harness on bare x-core.x: 19 failures).  It is priced now, in
# docs/numeric-gap.md: what breaks, what each of the four fixes costs, and
# why the answer waits on a release whose `x -l awk` boots from an image.
# Still the bundle's bug rather than the harness's, and still not the
# harness's to paper over.

# %install-root FIRST (deferred imports resolve against it), the amalgam
# (never a dialect entry -- those end by starting a REPL), then the bundle
# root armed exactly as run.x arms it.  Nothing under awk/ includes anything
# from the platform: re-including a platform module on a booted tower is a
# segfault, not an error (x-lang#515).  No collect of our own: x-base.x
# ends its boot with one, and the compiled tower leaves no garbage that
# needs a second (the interpreted tower did -- IMG=0, 161 of 167 dead
# without it; measured both ways 2026-09-06 on the way back).
cat > "$OUT" <<EOT
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
(import-path! "$BUNDLE")
(import awk/base)
(set! %repl-print %awk-repl-print)
EOT
